# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-02-08 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20250208_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='portada'),
        ),
    ]
