# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-02-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_auto_20250208_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='website',
            field=models.URLField(max_length=30),
        ),
    ]
