# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-02-10 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_auto_20250208_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
