# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-02-10 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_auto_20250210_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
